pages:
  image:
    name: squidfunk/mkdocs-material:7.1.0
    entrypoint: [""]
  stage: deploy
  only:
    - master
  script:
    - mkdocs build --clean --site-dir public
  artifacts:
    paths:
      - public
