"MD038": false
"MD033": false # inline html
"MD013": false # line-length
"MD034": false # allow bare links
"MD040": false # fenced code blocks should have language selected
"MD053": false # do not remove mkdocs materials footnotes
