site_name: Learn SR Linux
nav:
  - Home: index.md

theme:
  name: material
  custom_dir: docs/overrides

  features:
    - navigation.top
    - navigation.tabs

  language: en
  font:
    text: Roboto # trying embedded font instead of a NokiaPureText
    code: Fira Mono
  logo: images/srlinux.svg # this doesn't work. Comment out to see that it works

# Plugins
plugins:
  - social

# Extensions

extra_css:
  - stylesheets/nokia.css
