site_name: Learn SR Linux
nav:
  - Home: index.md
  - Community: community.md

site_author: SR Linux
site_description: >-
  Learn SR Linux
# Repository
repo_name: srl-labs/learn-srlinux
repo_url: https://github.com/srl-labs/learn-srlinux
edit_uri: edit/main/docs/
site_url: "https://learn.srlinux.dev/"
copyright: Copyright &copy; 2021 Nokia
theme:
  name: material
  custom_dir: docs/overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - toc.integrate

  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto # trying embedded font instead of a NokiaPureText
    code: Fira Mono
  logo: images/srlinux.svg
  favicon: images/srlinux.svg

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - social

# Customization
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/tZvgjQ6PZf
    - icon: fontawesome/brands/github
      link: https://github.com/srl-labs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ntdvps
  analytics:
    provider: google
    property: G-VNYX781Q48

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.md_in_html
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/nokia.css
  - stylesheets/nokia-fonts.css
