site_name: Learn SR Linux
nav:
  - Home: index.md
  - Get Started: get-started.md
  - Management:
      - mgmt/index.md
  # - Knowledge Base:
  #     - Hardware types: kb/hwtypes.md
  #     - Management interfaces: kb/mgmt.md
  #     - Configuration management: kb/cfgmgmt.md
  #     - Interfaces: kb/ifaces.md
  #     - Network instances: kb/netwinstance.md
  - Programmability:
      - programmability/index.md
      - YANG:
          - yang/index.md
          - YANG Browser: yang/browser.md
      - NDK:
          - ndk/index.md
          - Developers Guide:
              - NDK Architecture: ndk/guide/architecture.md
              - Agent Structure: ndk/guide/agent.md
              - Agent Installation & Operations: ndk/guide/agent-install-and-ops.md
              - Environment Setup:
                  - Go: ndk/guide/env/go.md
                  - Python: ndk/guide/env/python.md
              - Developing with NDK:
                  - Go: ndk/guide/dev/go.md
                  - Python: ndk/guide/dev/python.md
          - App Catalog:
              - ndk/apps/index.md
              - EVPN Proxy: ndk/apps/evpn-proxy.md
              - kButler: ndk/apps/kbutler.md
              - Prometheus Telemetry Exporter: ndk/apps/srl-prom-exporter.md
              - Satellite Tracker: ndk/apps/satellite.md
      - Ansible:
          - ansible/index.md
          - Collection:
              - ansible/collection/index.md
              - get: ansible/collection/get.md
              - config: ansible/collection/config.md
              - validate: ansible/collection/validate.md
              - cli: ansible/collection/cli.md
  - Tutorials:
      # - SR Linux tutorials: tutorials/about.md
      - tutorials/index.md
      - EVPN:
          - Layer 2 EVPN:
              - Introduction: tutorials/l2evpn/intro.md
              - Fabric configuration: tutorials/l2evpn/fabric.md
              - EVPN configuration: tutorials/l2evpn/evpn.md
              - Summary: tutorials/l2evpn/summary.md
      - Infrastructure:
          - KNE:
              - tutorials/infrastructure/kne/index.md
              - Installation: tutorials/infrastructure/kne/installation.md
              - Topology: tutorials/infrastructure/kne/topology.md
              - SR Linux with Openconfig services:
                  - tutorials/infrastructure/kne/srl-with-oc-services/index.md
      - MPLS:
          - LDP-based MPLS:
              - Introduction: tutorials/mpls/mpls-ldp/intro.md
              - Routing: tutorials/mpls/mpls-ldp/routing.md
              - LDP: tutorials/mpls/mpls-ldp/ldp.md
      - Programmability:
          - Event Handler:
              - Oper Group:
                  - Introduction: tutorials/programmability/event-handler/oper-group/oper-group-intro.md
                  - Lab setup: tutorials/programmability/event-handler/oper-group/lab.md
                  - Problem statement: tutorials/programmability/event-handler/oper-group/problem-statement.md
                  - Configuring oper-group: tutorials/programmability/event-handler/oper-group/oper-group-cfg.md
                  - Script: tutorials/programmability/event-handler/oper-group/script.md
                  - Oper group in action: tutorials/programmability/event-handler/oper-group/opergroup-operation.md
                  - Summary: tutorials/programmability/event-handler/oper-group/summary.md
          - JSON-RPC:
              - Basics: tutorials/programmability/json-rpc/basics.md
              - Ansible: tutorials/programmability/json-rpc/ansible.md
  - Community: community.md
  - Blog:
      - blog/index.md
      - Subscribe: blog/subscribe.md
      - Tags: blog/tags.md
      - In the Media: blog/media.md

site_author: SR Linux
site_description: >-
  Open documentation for open Network OS
# Repository
repo_name: srl-labs/learn-srlinux
repo_url: https://github.com/srl-labs/learn-srlinux
edit_uri: edit/main/docs/
site_url: "https://learn.srlinux.dev/"
copyright: Copyright &copy; 2021-2023 Nokia
theme:
  name: material
  custom_dir: docs/overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - navigation.top
    # - navigation.instant # removed until code selection are fixed https://github.com/squidfunk/mkdocs-material/issues/5066
    - navigation.tabs
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - toc.follow
    - content.tooltips
    - navigation.indexes
    - announce.dismiss

  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: NokiaPureText
    code: Fira Code
  icon:
    logo: nokia/srlinux
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: images/srlinux.svg

# Plugins
plugins:
  - meta
  - glightbox
  - macros:
      j2_block_start_string: "[[[%"
      j2_block_end_string: "%]]]"
      j2_variable_start_string: "[[["
      j2_variable_end_string: "]]]"
      # include_yaml:
      #   - macros/data.yml
  - blog:
      blog_dir: blog
      post_url_date_format: yyyy
      archive: false
      categories: false
  - tags:
      tags_file: blog/tags.md
      # media.md is a file that only shows posts with `media` tag
      tags_extra_files:
        blog/media.md:
          - media
  - typeset
  - search
  - minify:
      minify_html: true
  - rss:
      match_path: blog/posts/.*
      abstract_chars_count: 5000
      date_from_meta:
        as_creation: date
      categories:
        - tags
      comments_path: "#__comments"
  - redirects:
      redirect_maps:
        "ndk/intro.md": "ndk/index.md"
        "yang/yang.md": "yang/index.md"

# Customization
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/tZvgjQ6PZf
    - icon: fontawesome/brands/github
      link: https://github.com/srl-labs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ntdvps
  analytics:
    provider: google
    property: G-VNYX781Q48
  tags:
    # tags and their identifiers
    media: media # media tag is used to show posts in media.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.md_in_html
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      line_spans: __span
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: srl-labs
      repo: learn-srlinux
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/nokia.css
  - stylesheets/nokia-fonts.css
  - stylesheets/diagrams.css
  - stylesheets/animations.css
