rdodin:
  name: Roman Dodin
  description: SR Linux PLM
  avatar: https://avatars.githubusercontent.com/u/5679861

jbemmel:
  name: Jeroen van Bemmel
  description: Webscale Architect
  avatar: https://avatars.githubusercontent.com/u/2031627
