rdodin:
  name: Roman Dodin
  description: SR Linux PLM
  avatar: https://avatars.githubusercontent.com/u/5679861

jbemmel:
  name: Jeroen van Bemmel
  description: Webscale Architect
  avatar: https://avatars.githubusercontent.com/u/2031627

sogawa:
  name: Satoshi Ogawa
  description: Webscale Solutions Architect
  avatar: https://avatars.githubusercontent.com/u/2031627

azyablov:
  name: Anton Zyablov
  description: Lead Solution Architect
  avatar: https://avatars.githubusercontent.com/u/22647209

mau:
  name: Mauricio Rojas
  description: Network Automation Consulting Engineer
  avatar: https://avatars.githubusercontent.com/u/69992138