---
name: CICD
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

env:
  MKDOCS_MATERIAL_VER: 3.2.3 # insiders version

jobs:
  docs-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker run -v $(pwd):/docs --entrypoint mkdocs ghcr.io/srl-labs/mkdocs-material-insiders:$MKDOCS_MATERIAL_VER build --clean --strict

      - name: Cache htmltest external links
        id: cache-htmltest
        uses: actions/cache@v2
        with:
          path: tmp/.htmltest
          key: htmltest

      - name: htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: docs/htmltest.yml

  publish-docs:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/heads/main')
    needs: docs-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker run -v $(pwd):/docs --entrypoint mkdocs ghcr.io/srl-labs/mkdocs-material-insiders:$MKDOCS_MATERIAL_VER gh-deploy --force --strict
